### ISSUE TITLE
request of robot-specfic ROS setting files. e.g. URDF

### ISSUE THREAD

**Issue by mfkenson** [PacktPublishing/Artificial-Intelligence-for-Robotics#10]
I have ordered the exact hardware and tried to following your path to create the same environment.
Could you share the ROS source/driver files? (e.g. ROS workspace)

**Comment by FGovers** [comment]
I'd be happy to but I'm not quite sure how to package that up. I've been working on moving the code to the windows version of ROS that runs under WSL (Windows System for Linux).   The version of ROS in the book is Lunar Loggerhead (ros.org/lunar/installation/ubuntu) running on 16.04.3 Ubuntu.  I took care not to create any custom environments under ROS, so the plain version should do everything you need.  The only problem I encountered is that I had to hand install Mycroft and the Google Voice drivers from source rather than use an image.  If I had tried to use the Google AI image, or the Mycroft image (.iso) it would have wiped out my ROS and Keras/Tensorflow setup

**Comment by mfkenson** [comment]
How about just zipping the whole catkin_ws directory and upload it to google drive? I think I could make a step by step tutorial for other beginners.

In case you don’t expose the files publicly, you could share the files with my google account ( mfkenson@gmail.com ). I can package the stuff later and publish.

**Comment by FGovers** [comment]
I can do this. I'll put them in the supplemental github repository  https://github.com/FGovers/Artificial-Intelligence-for-Robotics (the Packt version must contain only what is actually in the book)

**Comment by mfkenson** [comment]
Thank you @FGovers.
By the way you may want to upload binary files (e.g. zip) in release section of github.

**Comment by mfkenson** [comment]
@FGovers any news?
