### ISSUE TITLE
Indexed Qlearning Script [armTrainingQlearnIndexed.py] contains foreign variables

### ISSUE THREAD

**Issue by leocorp96** [PacktPublishing/Artificial-Intelligence-for-Robotics#8]
Hello, I find it quite confusing and would like some clarification if any, as to why we are accessing the Qmatrix using an undefined index in **line 178** of the script (armTrainingQlearnIndexed.py). 
Are we doing this to deliberately to throw the exception? Or could someone tell me what is happening here? 
Because changing **"statQ"** (which isn't defined anywhere) to **"stat"** (which maybe the intended variable) causes the training to output very different results.

This really is giving me a head spin.

**Comment by FGovers** [comment]
Leocorp:  You are correct - the variable should be "stat" and not statQ - however - changing this variable causes the program to fail and not converge to any solution at all.  I'm looking this over and there is not a quick fix.  Part 1).  This q learning system works better just picking random actions than it does using the q-learned past states, which is a bit strange.  That is because there are too many states to choose from, and it's not finding the exact state twice - each is different by a small amount.  We need to cut these states down to something more abstract.  I think that by rounding off the position of the motors to the nearest 10 would reduce the states to a manageable number.  As I noted in the book, using Q learning like I did was not a good approach for the robot arm problem and the Genetic Algorithm did a much better job.  Still, this procedure should work.  

I'll spend some more time on this and see if I can't fix this.
